[global]
# Streamlit Cloud deployment configuration
developmentMode = false

[server]
# Server configuration
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
# Theme configuration (users can still switch)
primaryColor = "#2b1e66"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[runner]
# Runner configuration
magicEnabled = true

[logger]
# Logger configuration
level = "info"
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s" 